- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

- name: Hello World Sample
  hosts: localhost
  connection: local
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"